# Generated by Django 5.0 on 2023-12-19 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_alter_categoria_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriapadre',
            name='id_categoriahijo',
            field=models.ForeignKey(db_column='id_categoriahijo', on_delete=django.db.models.deletion.CASCADE, related_name='categoria_padre_hijo', to='webapp.categoria'),
        ),
        migrations.AlterField(
            model_name='categoriapadre',
            name='id_categoriapadre',
            field=models.ForeignKey(db_column='id_categoriapadre', on_delete=django.db.models.deletion.CASCADE, related_name='categoria_padre_padre', to='webapp.categoria'),
        ),
    ]
