# Generated by Django 5.0 on 2023-12-19 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_marca'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_sunat', models.CharField(max_length=2)),
                ('denominacion', models.CharField(max_length=100)),
            ],
        ),
    ]
