# Generated by Django 5.0 on 2023-12-19 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_unidadmedida'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denominacion', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
                ('id_marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.marca')),
                ('id_unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.unidadmedida')),
            ],
        ),
    ]
