# Generated by Django 5.0 on 2023-12-19 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_productocategoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoPrecio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.FloatField()),
                ('fechavigencia', models.DateField()),
                ('estado', models.BooleanField(default=False)),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.producto')),
            ],
        ),
    ]
