# Generated by Django 5.0 on 2023-12-19 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0015_persona'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='id_tipo_documento',
            new_name='id_tipodocumento',
        ),
    ]
