# Generated by Django 5.0 on 2023-12-20 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0017_operador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.CharField(max_length=12)),
                ('correlativo', models.CharField(max_length=12)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('subtotal', models.FloatField()),
                ('igv', models.FloatField()),
                ('total', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_zona', models.CharField(max_length=100)),
                ('nombre_via', models.CharField(max_length=100)),
                ('manzana', models.CharField(max_length=2)),
                ('lote', models.CharField(max_length=2)),
                ('numero', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Nacionalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_sunat', models.CharField(max_length=2)),
                ('denominacion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PersonaJuridica',
            fields=[
                ('id_persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='webapp.persona')),
                ('razon_social', models.CharField(max_length=100)),
                ('nombre_comercial', models.CharField(max_length=100)),
                ('sitio_web', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denominacion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_sunat', models.CharField(max_length=2)),
                ('denominacion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denominacion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoComprobante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_sunat', models.CharField(max_length=2)),
                ('denominacion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDireccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denominacion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoTelefono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denominacion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoVia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_sunat', models.CharField(max_length=2)),
                ('denominacion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoZona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_sunat', models.CharField(max_length=2)),
                ('denominacion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ubigeo',
            fields=[
                ('ubigeo', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('departamento', models.CharField(max_length=100)),
                ('provincia', models.CharField(max_length=100)),
                ('distrito', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denominacion', models.CharField(max_length=100)),
                ('id_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.area')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField()),
                ('precio_unitario', models.FloatField()),
                ('subtotal', models.FloatField()),
                ('id_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.compra')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.persona')),
            ],
        ),
        migrations.AddField(
            model_name='compra',
            name='id_proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.proveedor'),
        ),
        migrations.CreateModel(
            name='PersonaNatural',
            fields=[
                ('id_persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='webapp.persona')),
                ('nombres', models.CharField(max_length=100)),
                ('apaterno', models.CharField(max_length=100)),
                ('amaterno', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('id_nacionalidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.nacionalidad')),
                ('id_sexo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.sexo')),
            ],
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('id_direccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.direccion')),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.cargo')),
                ('id_persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.persona')),
                ('id_rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.rol')),
                ('id_sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.sucursal')),
            ],
        ),
        migrations.CreateModel(
            name='SucursalSerie',
            fields=[
                ('serie', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('id_sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.sucursal')),
                ('id_tipocomprobante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.tipocomprobante')),
            ],
        ),
        migrations.CreateModel(
            name='Telefono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=100)),
                ('id_operador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.operador')),
                ('id_tipotelefono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.tipotelefono')),
            ],
        ),
        migrations.CreateModel(
            name='PersonaTelefono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.persona')),
                ('id_telefono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.telefono')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='webapp.persona')),
                ('id_tipocliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.tipocliente')),
            ],
        ),
        migrations.AddField(
            model_name='compra',
            name='id_tipocomprobante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.tipocomprobante'),
        ),
        migrations.CreateModel(
            name='PersonaDireccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('id_direccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.direccion')),
                ('id_persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.persona')),
                ('id_tipodireccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.tipodireccion')),
            ],
        ),
        migrations.AddField(
            model_name='direccion',
            name='id_tipovia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.tipovia'),
        ),
        migrations.AddField(
            model_name='direccion',
            name='id_tipozona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.tipozona'),
        ),
        migrations.AddField(
            model_name='direccion',
            name='id_ubigeo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.ubigeo'),
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('subtotal', models.FloatField()),
                ('igv', models.FloatField()),
                ('total', models.FloatField()),
                ('id_cajero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cajero_ventas', to='webapp.empleado')),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.cliente')),
                ('id_vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendedor_ventas', to='webapp.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtotal', models.FloatField()),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.producto')),
                ('id_productoprecio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.productoprecio')),
                ('id_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.venta')),
            ],
        ),
        migrations.CreateModel(
            name='ComprobanteVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correlativo', models.CharField(max_length=100)),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.sucursalserie')),
                ('id_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.venta')),
            ],
        ),
    ]
