# Generated by Django 5.0 on 2023-12-20 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0018_compra_direccion_nacionalidad_personajuridica_rol_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personadireccion',
            name='descripcion',
        ),
    ]
