# Generated by Django 5.0 on 2023-12-26 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0020_oficio_personaoficio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personatelefono',
            name='id_persona',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='webapp.persona'),
        ),
    ]
