# Generated by Django 5.0 on 2023-12-26 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0021_alter_personatelefono_id_persona'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personatelefono',
            name='id_persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.persona'),
        ),
    ]
