# Generated by Django 5.0 on 2023-12-27 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0023_alter_proveedor_id_persona'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleventa',
            name='cantidad',
            field=models.FloatField(default=0),
        ),
    ]
